environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYWHEEL_INFIX: "cp36"

init:
  - "ECHO %PYTHON% %APPVEYOR_REPO_TAG_NAME%"

install:
  - "C:\\Miniconda36\\Scripts\\conda.exe create -y -n faf pip"
  - "C:\\Miniconda36\\Scripts\\activate.bat faf"
  - "pip install cx_freeze"
  # dump version
  - git describe --tags --always
  - ps: "$env:TCL_LIBRARY = \"C:\\Miniconda36\\envs\\faf\\tcl\""
  - ps: "$env:TK_LIBRARY = \"C:\\Miniconda36\\envs\\faf\\tcl\""
  - ps: "$env:faf_version = \"0.1.0\""
  - "python setup.py bdist_msi"

artifacts:
  - path: '**\*.msi'

deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    auth_token:
      secure: "09WRxoB8lu9lPzuk3qYu0brKVQubLpnsS1Wdn49nYZYi5RDiva3z37eITcjtZkTD"
    artifact: /.*\.msi/
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: true

build: off
